production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
development:
  adapter: postgresql
  database: stoop_db
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: stoop_test
  pool: 5
  timeout: 5000
