development:
  server: "http://localhost:9292/faye"
  secret_token: ENV['FAYE_SECRET_TOKEN']
test:
  server: "http://localhost:9292/faye"
  secret_token: ENV['FAYE_SECRET_TOKEN']
production:
  server: ENV['FAYE_ENDPOINT']
  secret_token: ENV['FAYE_SECRET_TOKEN']
  signature_expiration: 3600 # one day
